// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZGgLT_AixDiEweE_paakUg0Svri_nllo',
    appId: '1:575785652048:web:05d7e098f9266b1b1b6655',
    messagingSenderId: '575785652048',
    projectId: 'coursefy-6bc1d',
    authDomain: 'coursefy-6bc1d.firebaseapp.com',
    storageBucket: 'coursefy-6bc1d.firebasestorage.app',
    measurementId: 'G-LHFM056FGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBncRFkL0OciiuOstH7FfkPKlGd8mZcq50',
    appId: '1:575785652048:android:9a47450aee80e3261b6655',
    messagingSenderId: '575785652048',
    projectId: 'coursefy-6bc1d',
    storageBucket: 'coursefy-6bc1d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpVCkXnfYvqgNEDe5VgOidx3sg4RtPt1g',
    appId: '1:575785652048:ios:461b921e045a31121b6655',
    messagingSenderId: '575785652048',
    projectId: 'coursefy-6bc1d',
    storageBucket: 'coursefy-6bc1d.firebasestorage.app',
    iosBundleId: 'com.myapp.coursefy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpVCkXnfYvqgNEDe5VgOidx3sg4RtPt1g',
    appId: '1:575785652048:ios:461b921e045a31121b6655',
    messagingSenderId: '575785652048',
    projectId: 'coursefy-6bc1d',
    storageBucket: 'coursefy-6bc1d.firebasestorage.app',
    iosBundleId: 'com.myapp.coursefy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDZGgLT_AixDiEweE_paakUg0Svri_nllo',
    appId: '1:575785652048:web:bd5417f5e42e48861b6655',
    messagingSenderId: '575785652048',
    projectId: 'coursefy-6bc1d',
    authDomain: 'coursefy-6bc1d.firebaseapp.com',
    storageBucket: 'coursefy-6bc1d.firebasestorage.app',
    measurementId: 'G-E8HKRTDETX',
  );
}
