name: coursefy
description: "Courses Application"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.6.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0  # Necesario para traducciones

  # Firebase y Google Sign-In
  firebase_core: ^3.10.0
  cloud_firestore: ^5.6.1
  firebase_auth: ^5.4.0
  firebase_storage: ^12.4.0
  google_sign_in: ^6.2.2

  # Otras dependencias útiles
  fluttertoast: ^8.2.10
  font_awesome_flutter: ^10.8.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  generate: true  # Necesario para generar localización automática

  assets:
    - lib/l10n/  # Carpeta de archivos de traducción .arb

flutter_gen:
  l10n:
    arb-dir: lib/l10n
    template-arb-file: app_en.arb
    output-localization-file: app_localizations.dart
    output-class: AppLocalizations
    preferred-supported-locales: ["en", "es"]